
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    name: test
    url: jdbc:mysql://119.3.249.45:3307/test?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai #url
    username: root
    password: shydadada
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean , com.lc.aop.entity
  table:
    auto: update
  modol:
    pack: com.example.test.bean
  database:
    type: mysql
server:
  port: 8090
  tomcat:
    max-http-post-size: 0
  jetty:
    accesslog:
      time-zone: Asia/Shanghai

